<?php 
	$design = Mage::registry('design');
	$designData = $design->getData();
	$colorCollection = Mage::getModel('pdp/pdp')->getDesignColor($designData['id']);
	$colorOption = array();
	if ( count($colorCollection) > 0) {
		foreach($colorCollection as $option) {
			$colorOption [] = $option->getData();
		}
	}
	$collection = Mage::getModel('pdp/pdp')->getDesignCollection();
	$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'pdp/images/';
	$baseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);
?>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span6">	
			<div class="btn-group-top">
				<span class="title">Add PDP Template Style</span>
			</div>
		</div>
		<div class="span6">	
			<div class="action-panel">
				<div class="btn-group">
					<button class="btn" type="button" onclick="history.back();" class="btn"><span>Back</span></button>
				</div>
				<div class="btn-group">
					<button type="button" class="btn" onclick="tshirtStyleForm.submit();" class="btn"><span>Save Style</span></button>
				</div>
			</div>
		</div>
	</div>
	<div style="text-align: center; margin-bottom: 5px">
		<img width='150px' src='<?php echo $mediaUrl . $designData['filename'] ?>'/>
        <?php if ($designData['filename_back']!=''){ ?> 
		<img width='150px' src='<?php echo $mediaUrl . $designData['filename_back'] ?>'/>
        <?php } ?>
	</div>
</div>
<form class="form-horizontal" id="tshirt_color_form" name="tshirt_color_form" method="POST" action="<?php echo Mage::helper("adminhtml")->getUrl("pdp/adminhtml_pdp/savetshirtcolor/"); ?>" enctype="multipart/form-data">
	<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
	<input type="hidden" id="media_url" value="<?php echo $mediaUrl ?>" />
	<input type='hidden' value='<?php echo $designData['id'] ?>' name='design_id'/>
	<div id='tshirt'>
		<div class="container-fluid">
			<div class="row-fluid">
				<div class="span12">
					<?php $counter = 1; ?>
					<input type='hidden' name='counter' id='counter' value='<?php echo $counter ?>' />
					<table class="table table-bordered" id='tshirt_color_option'>
						<tr>
							<th>Color <span class="required">*</span></th>
							<th>Color Name</th>
							<th>Style Image</th>
							<th>Front Image <span class="required">*</span></th>
							<th>Back Image</th>
							<th>Sort</th>
							<th>Action</th>
						</tr>
						<tr>
							<td>
								<input type='text' class='span required-entry' id='colorpicker_1' name='color-image[1]' value='' />
							</td>
							<td>
								<input type='text' class='span' id='colorname_1' name='color-name[1]' value='' />
							</td>
							<td><input type='file' name='styleimage_1' /></td>
							<td><input type='file' class='required-entry' name='colorimage_1' /></td>
							<td><input type='file' class='' name='colorimageback_1' /></td>
							<td>
								<input type='text' class='span9 validate-digits' name='sort[1]' value=''/>
							</td>
							<td><button type='button' class="colorimage-option" id='removeimg_1'>Remove</button></td>
						</tr>
					</table>
					<button id='add_more_color_image' type='button'>Add More +</button>
				</div>
			</div>
		</div>
	</div>
</form>
<script type='text/javascript'>
	var tshirtStyleForm = new varienForm('tshirt_color_form', '');
	var designColor = jQuery.noConflict();
	designColor(function($){
		//Active default option after page loaded
		Tshirt.activeColorPicker('#colorpicker_1');
	});
</script>