<div class="slideshow-container">
	<ul class="slideshow">
		<li><a href="{{config path="web/secure/base_url"}}accessories/eyewear.html"><img src="{{media url="wysiwyg/slide-1.jpg"}}" alt="An eye for detail - Click to Shop Eye Wear" /></a></li>
		<li><a href="{{config path="web/secure/base_url"}}women.html"><img src="{{media url="wysiwyg/slide-2.jpg"}}" alt="Style solutions - covet-worthy styles in travel-friendly fabrics - Click to Shop Woman" /></a></li>
		<li><a href="{{config path="web/secure/base_url"}}men.html"><img src="{{media url="wysiwyg/slide-3.jpg"}}" alt="Wing man - hit the runway in stylish separates and casuals - Click to Shop Man" /></a></li>
        </ul>
<div class="slideshow-pager">&nbsp;</div>
<span class="slideshow-prev">&nbsp;</span> <span class="slideshow-next">&nbsp;</span></div>




<div class="homepage_content" >
  <div class="iossection">
    <div class="heading_wrapper">
      <h2><span>create case for your ios device</span></h2>
    </div>
    <div class="homeitem">
      <div class="thu"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/iphone_4s.jpg" width="223" height="297" /></div>
      <div class="pdname">Iphone 4S</div>
      <div class="tools">
        <div class="addwishlist"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/wishlist.jpg" width="19" height="17" /></div>
        <div class="startnow" data-product-id="890">Start Now</div>
        <div class="addcompare"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/compare.jpg" width="19" height="17" /></div>
      </div>
    </div>
    <div class="homeitem">
      <div class="thu"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/iphone_5.jpg" width="223" height="297" /></div>
      <div class="pdname">Iphone 5</div>
      <div class="tools">
        <div class="addwishlist"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/wishlist.jpg" width="19" height="17" /></div>
        <div class="startnow" data-product-id="890">Start Now</div>
        <div class="addcompare"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/compare.jpg" width="19" height="17" /></div>
      </div>
    </div>
    <div class="homeitem">
      <div class="thu"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/ipad.jpg" width="223" height="297" /></div>
      <div class="pdname">Ipad</div>
      <div class="tools">
        <div class="addwishlist"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/wishlist.jpg" width="19" height="17" /></div>
        <div class="startnow" data-product-id="893">Start Now</div>
        <div class="addcompare"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/compare.jpg" width="19" height="17" /></div>
      </div>
    </div>
  </div>
</div>


<div class="homepage_content" >
  <div class="iossection">
    <div class="heading_wrapper">
      <h2><span>create case for your android device</span></h2>
    </div>
    <div class="homeitem">
      <div class="thu"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/galexy_3.jpg" width="223" height="297" /></div>
      <div class="pdname">galaxy 3</div>
      <div class="tools">
        <div class="addwishlist"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/wishlist.jpg" width="19" height="17" /></div>
        <div class="startnow" data-product-id="891">Start Now</div>
        <div class="addcompare"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/compare.jpg" width="19" height="17" /></div>
      </div>
    </div>
    <div class="homeitem">
      <div class="thu"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/galexy_4.jpg" width="223" height="297" /></div>
      <div class="pdname">galaxy 4</div>
      <div class="tools">
        <div class="addwishlist"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/wishlist.jpg" width="19" height="17" /></div>
        <div class="startnow" data-product-id>Start Now</div>
        <div class="addcompare"><img src="http://www.udesingify.com/skin/frontend/rwd/default/images/compare.jpg" width="19" height="17" /></div>
      </div>
    </div>
  </div>
</div>


<div class="home_guara_wrapper" >
  <div class="home_guara_inner">
    <div class="">
      <h2 class="homeheading"><span class="">We guarantee you'll love it</span></h2>
    </div>
    <div></div>
    <div class="homecontentinner">
      <h3 class="">Best quality canvas in the world</h3>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
    </div>
    <div class="homecontentinner">
      <h3 class="">100% Love Guarantee</h3>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
    </div>
    <div class="homecontentinner">
      <h3 class="homeheading">PicturePerfect™</h3>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
    </div>
    <div class="homecontentinner">
      <h3 class="homeheading">Handcrafted</h3>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
    </div>
  </div>
</div>


<div class="homepage_content" >
  <div class="iossection">
    <div class="heading_wrapper">
      <h2><span>why us</span></h2>
    </div>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
    
  </div>
</div>
<span class="pdp_loading no-display"><span>Please wait...</span></span>
<div class="no-display">
	<div id="pdp_design_popup"></div>
</div>

