<!-- JS -->
<!--<script type="text/javascript" src="<?php //echo $this->getSkinUrl('pdp/js/jquery.min.js')?>"></script>-->
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pdp/frontend/js/ui/jquery-1.7.2.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pdp/frontend/js/html2canvas.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pdp/frontend/js/ui/colorpicker.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pdp/frontend/js/ui/eye.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pdp/frontend/js/ui/jquery-ui.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pdp/frontend/js/ui/jquery.ui.touch.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pdp/frontend/js/ui/utils.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pdp/frontend/js/ui/jquery.ui.rotatable.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pdp/frontend/js/ui/jquery.ui.rotatabletext.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pdp/frontend/js/jquery.colorbox.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pdp/frontend/js/paging.js')?>"></script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('pdp/frontend/js/design.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('pdp/frontend/js/paging.js')?>"></script>
<!-- CSS -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('pdp/frontend/css/jquery.ui.core.css') ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('pdp/frontend/css/colorpicker.css') ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('pdp/frontend/css/styles.css') ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('pdp/frontend/css/colorbox.css') ?>" />

			