<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('boxes.css') ?>">
<form id="add_new_side_form" method="POST" action="<?php echo Mage::helper("adminhtml")->getUrl("pdp/adminhtml_designarea/save/"); ?>" enctype="multipart/form-data">
	<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
	<input type="hidden" name="product_id" value="<?php echo Mage::app()->getRequest()->getParam('productid') ?>" />
	<div style="" id="designarea_tabs_form_section_content">
		<div class="entry-edit">
			<div class="entry-edit-head">
				<h4 class="icon-head head-edit-form fieldset-legend">Design Area Information</h4>

				<div class="form-buttons"></div>
			</div>
			<div id="pdpdesignarea_pdp_form" class="fieldset ">
				<div class="hor-scroll">
					<table cellspacing="0" class="form-list">
						<tbody>
						<tr>
							<td class="label"><label for="pdplabel">Label <span class="required">*</span></label></td>
							<td class="value">
								<input type="text" class="required-entry input-text required-entry" value="" name="label"
									   id="pdplabel"></td>
						</tr>
						<tr>
							<td class="label"><label for="pdpis_required">Is Required Area</label></td>
							<td class="value">
								<select class=" select" name="is_required" id="pdpis_required">
									<option value="2">No</option>
									<option value="1">Yes</option>
								</select></td>
						</tr>
						<tr>
							<td class="label"><label for="pdpposition">Position</label></td>
							<td class="value">
								<input type="text" class=" input-text" value="" name="position" id="pdpposition"></td>
						</tr>
						<tr>
							<td class="label"><label for="pdpstatus">Status</label></td>
							<td class="value">
								<select class=" select" name="status" id="pdpstatus">
									<option value="1">Enabled</option>
									<option value="2">Disabled</option>
								</select></td>
						</tr>
						<tr>
							<td class="label"></td>
							<td class="value"><button class="scalable save" type="submit" title="Save"><span><span><span>Save</span></span></span></button></td>
						</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</form>	