<?php
if (Mage::getStoreConfig('pdp/setting/enable') == 0) {	
	echo "<h3>PDP module is disabled. Please enable PDP to use it's features!</h3>";
}
$baseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);
$productId = Mage::app()->getRequest()->getParam('id');
$productStatus = Mage::getModel('pdp/productstatus')->getProductStatus($productId);
?>
<input type="hidden" id="current_product_id" value="<?php echo $productId ?>" />
<input type="hidden" id="base_url" value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK) ?>" />
<input type="hidden" id="request_url" value="<?php echo Mage::helper("adminhtml")->getUrl("pdp/adminhtml_designarea/setuparea") ?>" />
<input type="hidden" id="add_design_color_url" value="<?php echo Mage::helper("adminhtml")->getUrl("pdp/adminhtml_designarea/adddesigncolor") ?>" />
<input type="hidden" id="preview_design_color_url" value="<?php echo Mage::helper("adminhtml")->getUrl("pdp/adminhtml_designarea/previewdesigncolor") ?>" />

<div class="entry-edit">
    <div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Enable PDP Design</h4>
	</div>
    <div id="group_enable_pdp" class="fieldset fieldset-wide">
		<div class="hor-scroll">
			<div>
				<label>Enable PDP Design</label>
				<select name="enable_pdp_design">
					<option value=''><?php echo $this->__("--Please select--") ?></option>
					<option <?php echo ($productStatus == "1") ? "selected" : ''; ?> value="1"><?php echo $this->__("Yes") ?></option>
					<option <?php echo ($productStatus == "2") ? "selected" : ''; ?> value="2"><?php echo $this->__("No") ?></option>
				</select>
			</div>
		</div>
    </div>
</div>
<!--<div class="entry-edit">
	<div class="entry-edit-head">
		<h4>Design Sides</h4>
		<div class="right"><button style="" onclick="" class="scalable add" type="button" title="Add New Side" id="add_new_side"><span><span><span>Add New Side</span></span></span></button></div>
	</div>
	<div id="add_new_side_group" class="fieldset fieldset-wide">
		<div class="hor-scroll">
			Sides
		</div>
    </div>
</div>-->
<div class="entry-edit">
    <div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Setup design area and create sample design</h4>
		<div class="right">
			<button style="" onclick="" class="scalable add" type="button" title="Add New Side" id="add_new_side">
				<span><span><span>Add New Side</span></span></span>
			</button>
		</div>
	</div>
    <div id="group_pdp_sample" class="fieldset fieldset-wide">
		<div class="hor-scroll">
			<div class="side-table-container"></div>
		</div>
    </div>
</div>


<?php $sideTableUrl = Mage::helper("adminhtml")->getUrl("pdp/adminhtml_designarea/getsidetable"); ?>
<?php $enablePdpDesign = Mage::helper("adminhtml")->getUrl("pdp/adminhtml_designarea/updateStatus"); ?>
<?php $addNewSide = Mage::helper("adminhtml")->getUrl("pdp/adminhtml_designarea/addNewSide") . "productid/" . $productId; ?>
<script>
var mstPdpDesign = jQuery.noConflict();
mstPdpDesign(function($){
	$("#product_info_tabs_pdpdesign").click(function() {
		$.ajax({
			type:"GET",
			url: "<?php echo $sideTableUrl . "productid/$productId/isAjax=true" ?>",
			beforeSend:function(){
				$("#loading-mask").attr("style","left: -2px; top: 0px; width: 1034px; height: 833px; z-index: 10000;");
				$("#loading-mask").show();
			},
			success:function(data){
				if(data !== ""){
					$(".side-table-container").html(data);
					$("#loading-mask").hide();
				}else{
					console.log("Something went wrong");
				}
			}
		});
	});
	$("select[name='enable_pdp_design']").change(function() {
		if ($(this).val() != "") {
			$.ajax({
				type:"GET",
				url: "<?php echo $enablePdpDesign . "product_id/$productId/status/" ?>" + $(this).val() + "?isAjax=true",
				beforeSend:function(){
					$("#loading-mask").attr("style","left: -2px; top: 0px; width: 1034px; height: 833px; z-index: 10000;");
					$("#loading-mask").show();
				},
				success:function(data){
					if(data == ""){
						$("#loading-mask").hide();
					}else{
						console.log("Something went wrong");
					}
				}
			});
		}
	});
	$("#add_new_side").on("click", function() {
		PDPPopup.openPopup("<?php echo $addNewSide ?>", "Setup Design Area", PDPPopup.setupAreaHandler );
	});
});

</script>