<!--HTML for the tooltips-->
<div id="mystickytooltip" class="stickytooltip">
    <div style="padding:5px">
        <!--PDP Questions-->
        <div id="pdptt_questions" class="atip" style="width:200px">
            <p>Do you have any questions?</p><br /> 
            Contact me at: <a href="mailto:pdpmagento@gmail.com">pdpmagento@gmail.com</a>
        </div>
        <!--PDP Add Images-->
        <div id="pdptt_add_images" class="atip"  style="width:200px">
            <p>Insert Clipart or Upload a Photos</p>
        </div>
        <!--PDP Add Text-->
        <div id="pdptt_add_text" class="atip">
            <p>Add Text For Your Design</p>
        </div>
        <!--PDP Opacity-->
        <div id="pdptt_opacity" class="atip">
            <p>Setup Opacity for each item</p>
        </div>
    </div>
    <div class="stickystatus"></div>
</div>