<?php
	if (Mage::getStoreConfig('pdp/setting/enable') == 0) {
		echo "<h3>PDP module is disabled. Please enable PDP to use it's features!</h3>";
		return false;
	}
    //if(($_REQUEST['id']=='')||(!isset($_REQUEST['id']))||($_REQUEST['wid'])){
    //    echo "<h3>PDP module is enable. But you need to go from product page! How can you get this URL?</h3>";
	//	return false;
    //}
    $helper = Mage::helper('pdp');
    $imagePath = $helper->getImagePath();
    $fontPath = $helper->getFontPath();
    $baseImagePath = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'pdp/images/';
    //$customImages = $helper->getCustomImages();
    //$woodImages = $helper->getWoodImages();
    $fonts = $helper->getFonts();
    $designs = $helper->getDesignCollection();
    //print_r($dataedit);
    //if(isset($_REQUEST['id'])&&($_REQUEST['id']!='')){
    $cid = Mage::getSingleton('core/session')->getEditItem();    
    $editid = $_REQUEST['eid'];
    $wid = $_REQUEST['wid'];
    if($wid!=''){
        $pdpTemplate = Mage::getModel('pdp/pdptemplate')->load($wid);
        $data = explode('ϣ',$pdpTemplate->getPdpDesign());
    }elseif($editid!=''){
        $dataedit = Mage::getSingleton('core/session')->getEditItem();
        $data = explode('ϣ',$dataedit[$editid]['info']);
    }elseif($cid!=''){
        $dataedit = Mage::getSingleton('core/session')->getCustomItem();
        $data = explode('ϣ',$dataedit);
    }
    //}
/////////////////////////////////////////////////////////////////////////////////////////////////////
    $cid = $productId = Mage::app()->getRequest()->getParam('id');
    $ct_ct = $_REQUEST['ct'];
    $cr_design = Mage::getSingleton('core/session')->getCrItem();
	$adminTemplate = Mage::helper('pdp')->getAdminTemplates($productId);
    //$productId = Mage::getStoreConfig('pdp/setting/productid');
    $product = Mage::getModel('catalog/product')->load($productId);
    //$price = Mage::helper('core')->currency($product->getPrice(),true,false);
    $price = $product->getPrice();
    $title = $product->getName();
    $shortDes = $product->getShortDescription();
    $fullDes = $product->getDescription();
    $_helper = $this->helper('catalog/output');
    //$data = explode('ϣ',$product->getResource()->getAttribute('custom_design_pdp')->getFrontend()->getValue($product));
    if($cr_design!=''){
        $data = explode('ϣ',$cr_design);
    }else{
        //$data = explode('ϣ',$product->getResource()->getAttribute('custom_design_pdp')->getFrontend()->getValue($product));
    }
    if($adminTemplate!=''){
        $data = explode('ϣ',$adminTemplate);
    }
    $dt_ts = explode(';',$data[0]);
    $ipedit = $dataip[0];
?>
<?php //echo $this->getLayout()->createBlock('core/template')->setTemplate('pdp/product/default_config.phtml')->toHtml(); ?>
<div class="wrapper_pdp">
	<input type="hidden" id="admin_template" value="<?php echo $adminTemplate; ?>"/>
	<!--Facebook-->
	<?php 
	$facebookAppId = $facebookKey = "";
	$facebookInfo = Mage::helper('pdp')->getFacebookSetting();
	if (is_array($facebookInfo)) {
		$facebookAppId = $facebookInfo['facebook_app_id'];
		$facebookKey = $facebookInfo['facebook_secret_key'];
	}
	?>
    <h2 class="product-title"><?php echo $title ?></h2>
    <div class="wrap_pdp_design">
        <div id="design_control">
            <div class="control_tab">
                <div class="control_tab_wrap">
                    <div class="t_shirt tab_main active" tab="t_shirt">
                        <a><?php echo $this->__("Select Item"); ?></a>
                    </div>
                    <div class="add_artwork_tab tab_main" tab="add_artwork">
                        <a><?php echo $this->__("Add Artwork") ?></a>
                    </div>
                    <div class="add_text_tab tab_main" tab="add_text">
                        <a><?php echo $this->__("Add Text") ?></a>
                    </div>
                </div>
            </div>
            <div id="select_phone_type" class="t_shirt tab_content">
                <div class="wrap_product_type">
                    <h3 class="product-type-title numbers first"><?php echo $this->__("Select Item Type") ?></h3>
            		<select id="t-shirt-type">
                        <?php 
                            $group_items = Mage::getModel( 'pdp/pdpgroup' )->getPdpGroup();
                            foreach ($group_items as $group_item ){ ?>
                                <option value='<?php echo $group_item->getId() ?>' <?php if($dt_ts[0]==$group_item->getId()) echo 'selected="selected"'; ?>><?php echo $group_item->getTitle() ?></option>
                            <?php }
                        ?>
                    </select>
                </div>
        		<div class="color_wrap no-display">
                    <h3 class="color-option"><?php echo $this->__("Select Item") ?></h3>
            		<div color="list" id="list_color">
            			<ul>
            			<?php $img_all = ''; $fi=0; foreach ($designs as $design) {
            			     if($dt_ts[4]==''){
            			         if($fi++==0){
                			         //$f_img_act = 'class="active"';
                			     }else{
                			         $f_img_act = '';
                                 }
            			     }else{
            			         if($dt_ts[4]==$design->getId()){
            			             $f_img_act = 'class="active"';
            			         }else{
                			         $f_img_act = '';
            			         }
            			     }
            				$option = unserialize($design->getOptions());
            				$frontInlay = $helper->getInlayInfoByFilename($design->getFilename());
            				$backInlay = $helper->getInlayInfoByFilename($design->getFilenameBack());
                            $img_all .= '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'pdp/images/'.$design->getFilenameBack().'" /><img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'pdp/images/'.$design->getFilename().'" />';
            				echo '<li '.$f_img_act.' did="'.$design->getId().'" inlay="'.$frontInlay . '-' . $backInlay .'" relf="'. $design->getFilename().'" relb="' . $design->getFilenameBack() .'" tt="'. $design->getPdpgroup() .'" price="'.$design->getPrice().'" ><img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'pdp/images/'.$design->getFilename().'" /></li>';
            			} ?>
            			</ul>
            		</div>
        			<div class='design-color-image'>
        				<?php $colorList = Mage::getModel('pdp/pdp')->getDesignStyles(); ?>
                        <h3 class="color-option"><?php echo $this->__("Choose Style:") ?>
                            <span class="color_name">&nbsp;</span><span class="color_price">&nbsp;</span>
                        </h3>
        				<ul>
        					<?php 
        					foreach ($colorList as $color) {
        						$images = $color->getFilename() . ',' . $color->getFilenameBack();
        						$hexcode = $color->getHexcode();
        						$designId = $color->getDesignId();
								$styleImage = $color->getStyleImage();
                                if($color->getPrice()==''){
                                    $colorprice = 0;
                                }else{
                                    $colorprice= $color->getPrice();
                                }
                                if($dt_ts[5]=='cl_'.$color->getId()){
                                    $color_act = ' class="active"';
                                }else{
                                    $color_act = '';
                                } 
								if ($styleImage != "") {
									echo '<li name="'.$color->getColorName().'" price="'.number_format($colorprice,2).'" id="cl_'.$color->getId().'" design="'.$designId.'" relf="'. $color->getFilename() .'" '.$color_act.'  relb="'. $color->getFilenameBack() .'" color="'. $hexcode .'" styleimage="'. $hexcode .'"><img src="'. $baseImagePath . $styleImage  .'" /></li>';
								} else {
									echo '<li name="'.$color->getColorName().'" price="'.number_format($colorprice,2).'" id="cl_'.$color->getId().'" design="'.$designId.'" relf="'. $color->getFilename() .'" '.$color_act.'  relb="'. $color->getFilenameBack() .'" color="'. $hexcode .'" style="background:#'. $hexcode .'"></li>';
                                }
								$img_all .= '<img src="'.$baseImagePath . $color->getFilenameBack().'" /><img src="'.$baseImagePath . $color->getFilename().'" />';
        					} 
        					?>
        				</ul>
        			</div>
                </div>
                <div class="no-display" id="all_img_cache">
                <?php echo $img_all; ?>
                </div>
            </div>
            <div id="select_image" class="tab_content add_artwork no-display">
                <h3 class="phone-type-title numbers third"><?php echo $this->__("Choose in galleries images or upload your own") ?></h3>
                <div class="tab_design_image">
                    <a tab-content="content_designs" class="active design"><?php echo $this->__("Designs") ?></a>
                    <a tab-content="content_upload" class="upload">Uploads</a>
                    <?php if($facebookAppId!=''){ ?> 
                    <a tab-content="content_facebook" class="facebook_api">Facebook</a>
                    <?php } ?>
                </div>
                <div class="content_tab">
                    <div class="content_designs">
        				<?php $categoryOptions = Mage::getModel('pdp/artworkcate')->getCategoryOptions(); ?>
        				<ul id='image_category_list'>
        					<?php 
        					$options = $categoryOptions;
                            $check_first = 0;
        					foreach ($options as $key => $value) {
        					    if($check_first++==0){$act='class="active cat_loaded" cr_act="2"';}else{$act='';}
        						echo "<li ".$act."> <span id='". $key ."'>{$value}</span></li>";
        					}
        					?>
        				</ul>
        				<ul id="icon_list">
							<?php $defaultArtCate = Mage::getModel('pdp/artworkcate')->getDefaultArtCate() ?>
							<?php $pdpObject = new MST_Pdp_Block_Pdp(); ?>
        					<?php foreach ($pdpObject->pagingCollection(1, $defaultArtCate, $pdpObject->_default_page_size) as $image) : ?>
        					<li cat="<?php echo $image->getCategory(); ?>">
                                <a rel="clover" class="selection_img">
        							<?php $colorImg = Mage::getModel('pdp/pdp')->getColorImageFrontend($image->getId()); ?>
                                    <img src="<?php echo $imagePath . $image->getFilename()  ?>" id="img<?php echo $image->getId(); ?>" color="<?php echo $colorImg ?>" />
                                </a>
                            </li>
        					<?php endforeach; ?>
        				</ul>
        				<div class="add-more">
        					<input type="hidden" value='<?php echo $pdpObject->_default_page_size ?>' name='default_page_size' id="default_page_size" />
        					<button class="btn" id="load_more_image" type="button">Load More Image</button>
        				</div>
                    </div>
                    <div class="content_upload no-display">
                        <input type="file" id="files_upload" name="imgfiles[]" multiple="" />
                        <div id="lists_img_upload"></div>
                    </div>
                    <div class="content_facebook no-display">
                          <div id="fb-root"></div>
                          <div id="user-info"></div>
                          <div id="photos_album"></div>
                          <button id="fb-auth" type="button">Please login Facebook</button> 
                    </div>
                </div>
            </div>
            <div id="add_text" class="tab_content add_text">
                <h3 class="product-type-title numbers first"><?php echo $this->__("Add Text") ?></h3>
                <div class="add_text_field">
                    <!--<input placeholder="<?php echo $this->__('Add text...'); ?>" id="add_text_input"/> -->
                    <textarea placeholder="<?php echo $this->__('Add text...'); ?>"  maxlength="100" id="add_text_input"></textarea>
                    <div id="change_text_type">
                        <ul>
                            <li><a class="text bold">B</a></li>
                            <li><a class="text italic">I</a></li>
                            <li><a class="text underline">U</a></li>
                            <li><a class="align align_left active">L</a></li>
                            <li><a class="align align_center">C</a></li>
                            <li><a class="align align_right">R</a></li>
                            <li><a class="align align_justify">J</a></li>
                        </ul>
                    </div>
                    <div class="change_font">
                        <div class="box_text">
                            <label><?php echo $this->__("Text Font") ?></label>
                            <span id="select_font_span"><?php echo $this->__('Arial'); ?></span>
                            <ul id="select_font">
                                <li rel="<?php echo $this->__("Arial") ?>"><?php echo $this->__("Arial") ?></li>
                                <?php foreach ( $fonts as $font) : ?>
                                <li rel="<?php echo $font->getName() ?>"><?php echo $font->getName() ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <div class="box_font_size">
                            <label><?php echo $this->__("Font size") ?></label>
                            <div class="select_font_size">
                                <span class="prev_t">Prev</span>
                                <input type="text" value="20" id="select_font_size" />
                                <span class="next_t">Next</span>
                            </div>
                        </div>
                        <div class="box_color">
                            <label>Font Color</label>
                            <div id="font_color_div"><div class="color_display" style="background-color: #444444"></div></div>
                        </div>
                        <div class="font_shape">
                            <div class="font_outline_color">
                                <div class="use_shadow">
                                    <input type="checkbox" name="use_shadow" id="use_shadow" value="0" />
                                    <label for="use_shadow">Text outline color</label>
                                </div>
                                <div class="h-shadow no-display">
                                    <label>h-shadow</label> 
                                    <span class="prev_t">Prev</span>
                                    <input type="text" value="0" id="h-shadow" />
                                    <span class="next_t">Next</span>
                                </div>
                                <div class="v-shadow no-display">
                                    <label>v-shadow</label> 
                                    <span class="prev_t">Prev</span>
                                    <input type="text" value="0" id="v-shadow" />
                                    <span class="next_t">Next</span>
                                </div>
                                <div class="blur no-display">
                                    <label>blur</label> 
                                    <span class="prev_t">Prev</span>
                                    <input type="text" value="0" id="t-blur" />
                                    <span class="next_t">Next</span>
                                </div>
                                <div class="color no-display">
                                    <label>color</label>
                                    <div id="font_outline_color"><div class="color_display" style="background-color: #ffffff"></div></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clear"></div>
                    <div id="add_text_action" title="Add text">
                        <span><?php echo $this->__('Add Text'); ?></span>
                    </div>
                    <!--
        <div id="edit_text_action" class="no-display" title="Edit text">
                        <span><?php echo $this->__('Edit Text'); ?></span>
                    </div>
        -->
                </div>        
            </div>
            <div id="edit_item_wrap">
                <label><?php echo $this->__('Edit Item'); ?></label>
                <div id="move_item">
                    <span class="m_tl">TL</span>
                    <span class="m_tc">TC</span>
                    <span class="m_tr">TR</span>
                    <span class="m_cl">CL</span>
                    <span class="m_cc">CC</span>
                    <span class="m_cr">CR</span>
                    <span class="m_bl">BL</span>
                    <span class="m_bc">BC</span>
                    <span class="m_br">BR</span>
                </div>
                <div id="duplicate_item">
                    <span><?php echo $this->__('Duplicate'); ?></span>
                </div>
                <div id="delete_item">
                    <span><?php echo $this->__('Delete'); ?></span>
                </div>
                <!--
        <div id="move_rotate">
                    <span class="move_to_front"><?php echo $this->__('Move to front'); ?></span>
                    <span class="move_to_back"><?php echo $this->__('Move to back'); ?></span>
                </div>
        -->
                <div id="flip_items">
                    <span class="flip_x"><?php echo $this->__('Flip X'); ?></span>
                    <span class="flip_y"><?php echo $this->__('Flip Y'); ?></span>
                </div>
            </div>
            <div class='save-design'>
                <button id="save_design_btn_backend" type="button"><span><span>Save Design</span></span></button>
            </div>
        </div>
        <div class="product-img-box">
            <div id="rotate-180"><a class="fback"><?php echo $this->__("180") ?></a></div>
            <div class="product-image act" id="product-image-wrap-front">
                <div id="wrap_inlay_front" class="wrap_inlay">
                    <?php for($i=1;$i<count($data);$i++){ 
                        $datass= explode('╦',$data[$i]);
                        if($datass[0]=='front'){
                            if(count($datass)==10){ ?>
                                <div class="item image_item" scx="<?php echo $datass[8] ?>" scy="<?php echo $datass[9] ?>" angle2="<?php echo $datass[1] ?>" w="<?php echo $datass[2] ?>" pos="<?php echo $datass[4] ?>"  h="<?php echo $datass[3] ?>" style="<?php echo $datass[5] ?>">
                                    <img style="<?php echo $datass[6] ?>" src="<?php echo $datass[7] ?>" />        
                                </div>
                            <?php }else { ?> 
                                <div class="item text-image" scx="<?php echo $datass[9] ?>" scy="<?php echo $datass[10] ?>" angle2="<?php echo $datass[1] ?>" w="<?php echo $datass[2] ?>" pos="<?php echo $datass[4] ?>"  h="<?php echo $datass[3] ?>" style="<?php echo $datass[5] ?>">
                                    <p style="<?php echo $datass[7] ?>"><?php echo $datass[8] ?></p>        
                                </div>
                            <?php } ?> 
                    <?php }} ?>   
                </div>
            </div>
            <div class="product-image" id="product-image-wrap-back">
                <div id="wrap_inlay_back" class="wrap_inlay">
                    <?php for($i=1;$i<count($data);$i++){
                        $datass= explode('╦',$data[$i]);
                        if($datass[0]=='back'){
                            if(count($datass)==10){ ?>
                                <div class="item image_item" scx="<?php echo $datass[8] ?>" scy="<?php echo $datass[9] ?>" angle2="<?php echo $datass[1] ?>" w="<?php echo $datass[2] ?>" pos="<?php echo $datass[4] ?>"  h="<?php echo $datass[3] ?>" style="<?php echo $datass[5] ?>">
                                    <img style="<?php echo $datass[6] ?>" src="<?php echo $datass[7] ?>" />        
                                </div>
                            <?php }else { ?> 
                                <div class="item text-image" scx="<?php echo $datass[9] ?>" scy="<?php echo $datass[10] ?>" angle2="<?php echo $datass[1] ?>" w="<?php echo $datass[2] ?>" pos="<?php echo $datass[4] ?>"  h="<?php echo $datass[3] ?>" style="<?php echo $datass[5] ?>">
                                    <p style="<?php echo $datass[7] ?>"><?php echo $datass[8] ?></p>        
                                </div>
                            <?php } ?>  
                    <?php }} ?> 
                </div>
            </div>
            <ul class="color_att"></ul>
        </div>
    </div>
	<?php //endif; ?>
    <div class="product-info">
        <div class="sort_des">
            <?php $gi = 0;  foreach ($group_items as $group_item ){  ?>
                <div class="group-des gdes_<?php echo $group_item->getId(); if($dt_ts[0]==$group_item->getId()) {}elseif(++$gi!=1){ echo ' no-display';} ?>">
            <?php
				$_cmsHelper = Mage::helper('cms');
				$_process = $_cmsHelper->getBlockTemplateProcessor();
				//echo $_process->filter($group_item['description']);
                //echo $group_item->getDescription();
                //break;
            ?>
            </div>
            <?php } ?>
        </div>   
        <div class="full_des">
            <?php //echo $_helper->productAttribute($_product, nl2br($product->getDescription()), 'description') ?>
            <?php //echo $fullDes ?>
        </div> 
    </div>
    <div id="img_sessiton" class="no-display">
        <?php //for($i=1;$i<count($data);$i++){ 
            //$datass= explode(';',$data[$i]);
        ?> 
        <?php //} ?>
    </div>
    <div class="no-display">
        <input type="hidden" id="login_url" value="<?php echo Mage::helper('customer')->getLoginUrl(); ?>" />
        <input type="hidden" value="<?php echo $_REQUEST['fb'] ?>" id="fb_get_id" />
        <input type="hidden" value="<?php echo $product->getProductUrl(); ?>" id="current_url" />
        <input type="hidden" value="<?php if($adminTemplate!=''){echo '1';}else{echo $wid; } ?>" id="wid" />
        <input type="hidden" value="<?php echo $cid ?>" id="cid" />
        <input type="hidden" value="<?php echo $_REQUEST['eid'] ?>" id="edit_id" />
        <input type="hidden" id="product_id" name="product_id" value="<?php echo Mage::app()->getRequest()->getParam('id'); ?>" />
		<input type="hidden" id="custom_price" name="custom_price" value="" />
        <input type="hidden" value="<?php echo Mage::getStoreConfig('web/unsecure/base_url');?>" id="url_site" />
        <input type="hidden" value="<?php echo $this->getSkinUrl('pdp/') ?>" id="skin_url" />
    	<input type="hidden" id="facebook_app_id" value="<?php echo $facebookAppId; ?>"/>
    	<input type="hidden" id="facebook_secret_key" value="<?php echo $facebookKey; ?>"/>
    </div>
</div>
<script type="text/javascript">
var facebook_app_id = '<?php echo $facebookAppId; ?>';
(function() {
  var e = document.createElement('script'); e.async = true;
  e.src = document.location.protocol 
    + '//connect.facebook.net/en_US/all.js';
  document.getElementById('fb-root').appendChild(e);
}());
</script>
<?php
$helper = Mage::helper('pdp');
$fonts = $helper->getFonts();
?>
<style type="text/css">
    <?php foreach ( $fonts as $font) { ?>
    @font-face {
        font-family: '<?php echo $font->getName() ?>';
        src: url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>pdp/fonts/<?php echo $font->getName() ?>.<?php echo $font->getExt() ?>');
    }
    <?php } ?>
</style> 
<!--
<input type="hidden" id="base_dir22" name="base_dir22" value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?> " />
-->
<input type="hidden" id="url_site" value="<?php echo Mage::getUrl('', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>" />
<input type="hidden" id="base_dir" name="base_dir" value="<?php echo Mage::getBaseDir('base'); ?>" />
<input type="hidden" value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK).Mage::getStoreConfig('pdp/setting/urlkey'); ?>" id="pdp_uri_key" />
<div class="no-display color_content">
    <div class="inlay_div color"></div>
    <div class="color_content_wrap">
        <ul>
            <li><a style="background-color: #F0F8FF" title="AliceBlue">AliceBlue</a></li>
            <li><a style="background-color: #FAEBD7" title="AntiqueWhite">AntiqueWhite</a></li>
            <li><a style="background-color: #00FFFF" title="Aqua">Aqua</a></li>
            <li><a style="background-color: #7FFFD4" title="Aquamarine">Aquamarine</a></li>
            <li><a style="background-color: #F0FFFF" title="Azure">Azure</a></li>
            <li><a style="background-color: #F5F5DC" title="Beige">Beige</a></li>
            <li><a style="background-color: #FFE4C4" title="Bisque">Bisque</a></li>
            <li><a style="background-color: #000000" title="Black">Black</a></li>
            <li><a style="background-color: #FFEBCD" title="BlanchedAlmond">BlanchedAlmond</a></li>
            <li><a style="background-color: #0000FF" title="Blue">Blue</a></li>
            <li><a style="background-color: #8A2BE2" title="BlueViolet">BlueViolet</a></li>
            <li><a style="background-color: #A52A2A" title="Brown">Brown</a></li>
            <li><a style="background-color: #DEB887" title="BurlyWood">BurlyWood</a></li>
            <li><a style="background-color: #5F9EA0" title="CadetBlue">CadetBlue</a></li>
            <li><a style="background-color: #7FFF00" title="Chartreuse">Chartreuse</a></li>
            <li><a style="background-color: #D2691E" title="Chocolate">Chocolate</a></li>
            <li><a style="background-color: #FF7F50" title="Coral">Coral</a></li>
            <li><a style="background-color: #6495ED" title="CornflowerBlue">CornflowerBlue</a></li>
            <li><a style="background-color: #FFF8DC" title="Cornsilk">Cornsilk</a></li>
            <li><a style="background-color: #DC143C" title="Crimson">Crimson</a></li>
            <li><a style="background-color: #00008B" title="DarkBlue">DarkBlue</a></li>
            <li><a style="background-color: #008B8B" title="DarkCyan">DarkCyan</a></li>
            <li><a style="background-color: #B8860B" title="DarkGoldenRod">DarkGoldenRod</a></li>
            <li><a style="background-color: #A9A9A9" title="DarkGray">DarkGray</a></li>
            <li><a style="background-color: #006400" title="DarkGreen">DarkGreen</a></li>
            <li><a style="background-color: #BDB76B" title="DarkKhaki">DarkKhaki</a></li>
            <li><a style="background-color: #8B008B" title="DarkMagenta">DarkMagenta</a></li>
            <li><a style="background-color: #556B2F" title="DarkOliveGreen">DarkOliveGreen</a></li>
            <li><a style="background-color: #FF8C00" title="DarkOrange">DarkOrange</a></li>
            <li><a style="background-color: #9932CC" title="DarkOrchid">DarkOrchid</a></li>
            <li><a style="background-color: #8B0000" title="DarkRed">DarkRed</a></li>
            <li><a style="background-color: #E9967A" title="DarkSalmon">DarkSalmon</a></li>
            <li><a style="background-color: #8FBC8F" title="DarkSeaGreen">DarkSeaGreen</a></li>
            <li><a style="background-color: #483D8B" title="DarkSlateBlue">DarkSlateBlue</a></li>
            <li><a style="background-color: #2F4F4F" title="DarkSlateGray">DarkSlateGray</a></li>
            <li><a style="background-color: #00CED1" title="DarkTurquoise">DarkTurquoise</a></li>
            <li><a style="background-color: #9400D3" title="DarkViolet">DarkViolet</a></li>
            <li><a style="background-color: #FF1493" title="DeepPink">DeepPink</a></li>
            <li><a style="background-color: #00BFFF" title="DeepSkyBlue">DeepSkyBlue</a></li>
            <li><a style="background-color: #696969" title="DimGray">DimGray</a></li>
            <li><a style="background-color: #1E90FF" title="DodgerBlue">DodgerBlue</a></li>
            <li><a style="background-color: #B22222" title="FireBrick">FireBrick</a></li>
            <li><a style="background-color: #FFFAF0" title="FloralWhite">FloralWhite</a></li>
            <li><a style="background-color: #228B22" title="ForestGreen">ForestGreen</a></li>
            <li><a style="background-color: #FF00FF" title="Fuchsia">Fuchsia</a></li>
            <li><a style="background-color: #DCDCDC" title="Gainsboro">Gainsboro</a></li>
            <li><a style="background-color: #F8F8FF" title="GhostWhite">GhostWhite</a></li>
            <li><a style="background-color: #FFD700" title="Gold">Gold</a></li>
            <li><a style="background-color: #DAA520" title="GoldenRod">GoldenRod</a></li>
            <li><a style="background-color: #808080" title="Gray">Gray</a></li>
            <li><a style="background-color: #008000" title="Green">Green</a></li>
            <li><a style="background-color: #ADFF2F" title="GreenYellow">GreenYellow</a></li>
            <li><a style="background-color: #F0FFF0" title="HoneyDew">HoneyDew</a></li>
            <li><a style="background-color: #FF69B4" title="HotPink">HotPink</a></li>
            <li><a style="background-color: #CD5C5C" title="IndianRed">IndianRed</a></li>
            <li><a style="background-color: #4B0082" title="Indigo">Indigo</a></li>
            <li><a style="background-color: #FFFFF0" title="Ivory">Ivory</a></li>
            <li><a style="background-color: #F0E68C" title="Khaki">Khaki</a></li>
            <li><a style="background-color: #E6E6FA" title="Lavender">Lavender</a></li>
            <li><a style="background-color: #FFF0F5" title="LavenderBlush">LavenderBlush</a></li>
            <li><a style="background-color: #7CFC00" title="LawnGreen">LawnGreen</a></li>
            <li><a style="background-color: #FFFACD" title="LemonChiffon">LemonChiffon</a></li>
            <li><a style="background-color: #ADD8E6" title="LightBlue">LightBlue</a></li>
            <li><a style="background-color: #F08080" title="LightCoral">LightCoral</a></li>
            <li><a style="background-color: #E0FFFF" title="LightCyan">LightCyan</a></li>
            <li><a style="background-color: #FAFAD2" title="LightGoldenRodYellow">LightGoldenRodYellow</a></li>
            <li><a style="background-color: #D3D3D3" title="LightGray">LightGray</a></li>
            <li><a style="background-color: #90EE90" title="LightGreen">LightGreen</a></li>
            <li><a style="background-color: #FFB6C1" title="LightPink">LightPink</a></li>
            <li><a style="background-color: #FFA07A" title="LightSalmon">LightSalmon</a></li>
            <li><a style="background-color: #20B2AA" title="LightSeaGreen">LightSeaGreen</a></li>
            <li><a style="background-color: #87CEFA" title="LightSkyBlue">LightSkyBlue</a></li>
            <li><a style="background-color: #778899" title="LightSlateGray">LightSlateGray</a></li>
            <li><a style="background-color: #B0C4DE" title="LightSteelBlue">LightSteelBlue</a></li>
            <li><a style="background-color: #FFFFE0" title="LightYellow">LightYellow</a></li>
            <li><a style="background-color: #00FF00" title="Lime">Lime</a></li>
            <li><a style="background-color: #32CD32" title="LimeGreen">LimeGreen</a></li>
            <li><a style="background-color: #FAF0E6" title="Linen">Linen</a></li>
            <li><a style="background-color: #FF00FF" title="Magenta">Magenta</a></li>
            <li><a style="background-color: #800000" title="Maroon">Maroon</a></li>
            <li><a style="background-color: #66CDAA" title="MediumAquaMarine">MediumAquaMarine</a></li>
            <li><a style="background-color: #0000CD" title="MediumBlue">MediumBlue</a></li>
            <li><a style="background-color: #BA55D3" title="MediumOrchid">MediumOrchid</a></li>
            <li><a style="background-color: #9370DB" title="MediumPurple">MediumPurple</a></li>
            <li><a style="background-color: #3CB371" title="MediumSeaGreen">MediumSeaGreen</a></li>
            <li><a style="background-color: #7B68EE" title="MediumSlateBlue">MediumSlateBlue</a></li>
            <li><a style="background-color: #00FA9A" title="MediumSpringGreen">MediumSpringGreen</a></li>
            <li><a style="background-color: #48D1CC" title="MediumTurquoise">MediumTurquoise</a></li>
            <li><a style="background-color: #C71585" title="MediumVioletRed">MediumVioletRed</a></li>
            <li><a style="background-color: #191970" title="MidnightBlue">MidnightBlue</a></li>
            <li><a style="background-color: #F5FFFA" title="MintCream">MintCream</a></li>
            <li><a style="background-color: #FFE4E1" title="MistyRose">MistyRose</a></li>
            <li><a style="background-color: #FFE4B5" title="Moccasin">Moccasin</a></li>
            <li><a style="background-color: #FFDEAD" title="NavajoWhite">NavajoWhite</a></li>
            <li><a style="background-color: #000080" title="Navy">Navy</a></li>
            <li><a style="background-color: #FDF5E6" title="OldLace">OldLace</a></li>
            <li><a style="background-color: #808000" title="Olive">Olive</a></li>
            <li><a style="background-color: #6B8E23" title="OliveDrab">OliveDrab</a></li>
            <li><a style="background-color: #FFA500" title="Orange">Orange</a></li>
            <li><a style="background-color: #FF4500" title="OrangeRed">OrangeRed</a></li>
            <li><a style="background-color: #DA70D6" title="Orchid">Orchid</a></li>
            <li><a style="background-color: #EEE8AA" title="PaleGoldenRod">PaleGoldenRod</a></li>
            <li><a style="background-color: #98FB98" title="PaleGreen">PaleGreen</a></li>
            <li><a style="background-color: #AFEEEE" title="PaleTurquoise">PaleTurquoise</a></li>
            <li><a style="background-color: #DB7093" title="PaleVioletRed">PaleVioletRed</a></li>
            <li><a style="background-color: #FFEFD5" title="PapayaWhip">PapayaWhip</a></li>
            <li><a style="background-color: #FFDAB9" title="PeachPuff">PeachPuff</a></li>
            <li><a style="background-color: #CD853F" title="Peru">Peru</a></li>
            <li><a style="background-color: #FFC0CB" title="Pink">Pink</a></li>
            <li><a style="background-color: #DDA0DD" title="Plum">Plum</a></li>
            <li><a style="background-color: #B0E0E6" title="PowderBlue">PowderBlue</a></li>
            <li><a style="background-color: #800080" title="Purple">Purple</a></li>
            <li><a style="background-color: #FF0000" title="Red">Red</a></li>
            <li><a style="background-color: #BC8F8F" title="RosyBrown">RosyBrown</a></li>
            <li><a style="background-color: #4169E1" title="RoyalBlue">RoyalBlue</a></li>
            <li><a style="background-color: #8B4513" title="SaddleBrown">SaddleBrown</a></li>
            <li><a style="background-color: #FA8072" title="Salmon">Salmon</a></li>
            <li><a style="background-color: #F4A460" title="SandyBrown">SandyBrown</a></li>
            <li><a style="background-color: #2E8B57" title="SeaGreen">SeaGreen</a></li>
            <li><a style="background-color: #FFF5EE" title="SeaShell">SeaShell</a></li>
            <li><a style="background-color: #A0522D" title="Sienna">Sienna</a></li>
            <li><a style="background-color: #C0C0C0" title="Silver">Silver</a></li>
            <li><a style="background-color: #87CEEB" title="SkyBlue">SkyBlue</a></li>
            <li><a style="background-color: #6A5ACD" title="SlateBlue">SlateBlue</a></li>
            <li><a style="background-color: #708090" title="SlateGray">SlateGray</a></li>
            <li><a style="background-color: #FFFAFA" title="Snow">Snow</a></li>
            <li><a style="background-color: #00FF7F" title="SpringGreen">SpringGreen</a></li>
            <li><a style="background-color: #4682B4" title="SteelBlue">SteelBlue</a></li>
            <li><a style="background-color: #D2B48C" title="Tan">Tan</a></li>
            <li><a style="background-color: #008080" title="Teal">Teal</a></li>
            <li><a style="background-color: #D8BFD8" title="Thistle">Thistle</a></li>
            <li><a style="background-color: #FF6347" title="Tomato">Tomato</a></li>
            <li><a style="background-color: #40E0D0" title="Turquoise">Turquoise</a></li>
            <li><a style="background-color: #EE82EE" title="Violet">Violet</a></li>
            <li><a style="background-color: #F5DEB3" title="Wheat">Wheat</a></li>
            <li><a style="background-color: #FFFFFF" title="White">White</a></li>
            <li><a style="background-color: #F5F5F5" title="WhiteSmoke">WhiteSmoke</a></li>
            <li><a style="background-color: #FFFF00" title="Yellow">Yellow</a></li>
            <li><a style="background-color: #9ACD32" title="YellowGreen">YellowGreen</a></li>
            <!--
            <li><a class="pdp_color_ori" title="Original">Original</a></li>
            -->
            <li><label><?php echo $this->__('Selected Color:'); ?></label><input maxlength="6" id="selected_color" type="text" value="" /><a style="background-color: #FFF" class="selected_color" title="Wheat">Wheat</a></li></li>
            <li class="last"><a class="bt_done">Done</a></li>
        </ul>
    </div>
</div>