<!--<script src="<?php echo $this->getJSUrl('pdp/js/jquery-latest.js') ?>"></script>-->
<!--<script src="<?php //echo $this->getJSUrl('pdp/js/html2canvas.min.js')  ?>"></script>-->
<!--
<script src="<?php echo $this->getJSUrl('pdp/js/ui/jquery-ui.js') ?>"></script>
<script src="<?php echo $this->getJSUrl('pdp/js/ui/jquery.ui.touch.min.js') ?>"></script>
<script src="<?php echo $this->getJSUrl('pdp/js/ui/jquery.ui.rotatable.js') ?>"></script>
<script src="<?php echo $this->getJSUrl('pdp/js/ui/jquery.ui.rotatabletext.js') ?>"></script>

-->
<script type="text/javascript" src="<?php echo $this->getJSUrl('pdp/js/farbtastic.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getJSUrl('pdp/js/owl.carousel.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJSUrl('pdp/js/jquery.waitforimages.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJSUrl('pdp/js/jquery.nouislider.js')?>"></script>
<script src="<?php echo $this->getJSUrl('pdp/js/design.js') ?>"></script>
