<?php 
	$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'pdp/images/';
	$baseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);
	$categoryOptions = Mage::getModel('pdp/artworkcate')->getCategoryOptions();
?>
<div id="image-manage">
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span8">
				<span class="title">Manage Artworks</span>
			</div>
			<div class="span4">
				<div class="btn-group">
					<button class="btn">Action</button>
					<button data-toggle="dropdown" class="btn dropdown-toggle">
						<span class="caret"></span>
					</button>
					<ul class="dropdown-menu">
						<li><a id="select_item" href="#">Select Item(s)</a></li>
						<li><a id="select_all_item" href="#">Select All Items</a></li>
						<li><a id="uncheck_all_item" href="#">Unchecked All Items</a></li>
						<li class="divider"></li>
						<li><a id="delete_selected_item" href="#">Delete Selected Item(s)</a></li>
					</ul>
				</div>
				<div class="btn-group">
					<button class="btn" onclick="ImgItem.upload();"><span id="btn-file-title">Add New Artworks</span></button>
				</div>
			</div>
		</div>
	</div>
	<div class="mst_pagination">
		<?php
		# Paging a collection
		echo "<input type='hidden' name='current_page' value='1'>";
		echo "<input type='hidden' name='page_size' value='". $this->_default_page_size ."'>";
		$paging_collection = $this->getImageCollectionPaging(1, $this->_default_page_size, 'pdp/index/getImagePaging', '0');
		$imageList = $paging_collection['collection'];
		echo $paging_collection['paging_text'];
		# End paging a collection
		?>
	</div>
    <div class="tab-content">
        <div class="tab-pane active" id="image">
			<div class='image-contianer'>
				<input type='hidden' name='secret_key' id='secret_key' value='<?php echo Mage::helper("adminhtml")->getUrl("pdp/adminhtml_pdp/artworkcolorinfo/"); ?>'/>
				<div id='container' class="clickable clearfix">
					<?php foreach ($imageList as $image) {?>
						<div class='img-item'>
							<?php $addColorUrl = Mage::helper("adminhtml")->getUrl("pdp/adminhtml_pdp/artworkcolorinfo/",array("image_id"=> $image->getImageId())); ?>
							<img rel="<?php echo $addColorUrl ?>" src='<?php echo $mediaUrl . $image->getFilename() ?>' alt='' />
							<input type="checkbox" class="checkbox-item" id="img_<?php echo $image->getId() ?>" style="display:none;" />
						</div>
					<?php } ?>
				</div>
			</div>
		</div>
    </div>
    
	<input type="hidden" value="<?php echo $baseUrl ?>" name="base_url" id="base_url"/>
    
    <div id="upload-files-form" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <form name="demoFiler" id="demoFiler" enctype="multipart/form-data" action="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'adminhtml/default/default/pdp/upload.php'; ?>">
    		<input type="hidden" name="upload_file_type" value="custom" id="upload_file_type"/>
            <div class="modal-header">
    			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    			<h4 id="myModalLabel">Upload Artwork</h4>
    		</div>
    		<div class="modal-body">
				<div>
					<span class='support-files'>Supported Image Formats : <b>.jpg, .jpeg, .png, .gif, .bmp, .svg</b></span>
				</div>
            	<div class="container-fluid">
            		<div class="row-fluid">
            			<div class="span12">
            				<div class="multiupload">
            					<div id="dragAndDropFiles" class="uploadArea">
            						
            					</div>
            					<?php //$adminobj= new Mage_Adminhtml_Block_Template(); ?>
            					<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
            					<input type="hidden" id="base_dir" name="base_dir" value="<?php echo Mage::getBaseDir(); ?>" />
            					<input type="hidden" id="skin_url" name="skin_url" value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>" />
								<input type="hidden" id="js_url" value="<?php echo $this->getJsUrl('pdp/images/') ?>" />
            					<div>
									<label for='image_category'>Choose Category</label>
            						<select id='image_category' name='image_category[]'>
										<option value=''><?php echo $this->__('--Please select--'); ?></option>
										<?php 
										$options = $categoryOptions;
										foreach ($options as $key => $value) {
											echo "<option value='". $key ."'>{$value}</option>";
										}
										?>
									</select>
            					</div>
								<div>
            						<input type="file" name="multiUpload" id="multiUpload" multiple="" /> 
            					</div>
            					<div class="progressBar">
            						<div class="status"></div>
            					</div>
            				</div>
            			</div>
            		</div>
            	</div>
    		</div>
    		<div class="modal-footer">
                <input type="submit" name="submitHandler" id="submitHandler" value="Upload" class="buttonUpload btn btn-primary" />
    		</div>
        </form>
	</div>
	<!--Image Model-->
	<div id="image-form" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h4 id="myModalLabel">Manage Artwork Colors</h4>
		</div>
		<div class="modal-body">
			<div class="container-fluid">
				<div class="row-fluid">
					<div class="span3">
						<div class='main-image'>
							<img id='edit_image' width="100px" src=""/>
						</div>
						<div class='category-name'>
							<span></span>
						</div>
					</div>
					<div class="span9">
						<div class="tab-pane" id="image-color-tab" style='text-align: center;'>
							<input type="hidden" value="<?php echo $mediaUrl ?>" name="media_url" id="media_url"/>
							<table id="edit_color_image" class="table table-bordered">
									
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<input type="hidden" value="" name="image_id" id="image_id" />
			<input type="button" name="add_new_color" id="add_new_color" value="Add Colors" onclick="" class="btn btn-primary" />
		</div>
	</div>
	<!--Add Color Modal-->
	<div class="add-color-form">
		<form class="form-horizontal" id="design-form" name="design-form" method="POST" action="<?php echo Mage::helper("adminhtml")->getUrl("pdp/adminhtml_pdp/savecolor/"); ?>" enctype="multipart/form-data">
			<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
			<div id="colorModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
					<h4 id="myModalLabel">Add New Image - Color</h4>
				</div>
				<div class="modal-body">
					<input type="hidden" value="" name="image_id_color" id="image_id_color"/>
					<div class="control-group">
						<label class="control-label" for="color_image">Image</label>
						<div class="controls">
							<input type="file" name="color_image" onchange="ImgItem.previewColorImage(this)"/>
						</div>
					</div>
					<div class="control-group">
						<label class="control-label">Preview Image</label>
						<div class="controls">
							<img id="designImage" src="" alt="Image will show here" width="150px" />
						</div>
					</div>
					<div class="control-group">
						<label class="control-label">Color</label>
						<div class="controls">
							
							<div class="row-fluid show-grid">
								<div class="span1">
									<div id="colorSelector">
										<div style="background: #ccc"></div>
									</div>
								</div>
								<div id="previewColor" style=""><input type="text" class="span12" value="" name="color" id="color" /></div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
					<button type="submit" class="btn">Save Color</button>
				</div>
			</div>
		</form>
	</div>
</div>