<?php 
	$colors = Mage::getModel('pdp/color')->getColors();
?>
<div class="pdp_color_list">
    <ul>
    <?php $i = 0; foreach($colors as $color)  :?>
         <li><a style="background-color: <?php echo $i > 0 ? '#' : ''; ?><?php echo $color->getColor_code(); ?>" title="<?php echo $color->getColor_name(); ?>"><?php echo $color->getColor_name(); ?></a></li>
        <?php $i++; endforeach;  ?>
    </ul>
</div>