<?php
$currentProduct =  Mage::registry('current_product');
$params = Mage::app()->getRequest()->getParams();
$productId = $currentProduct->getId();
$productStatus = Mage::getModel('pdp/productstatus')->getProductStatus($productId);
if ($productStatus != 1) {
    return false;
}
$action = $shareId = "";
if (isset($params['action'])) {
	$action = $params['action'];
}
if (isset($params['share'])) {
	$shareId = $params['share'];
}
?>
<div style="display: none">
	<a id="pdp_design_button" class="not_load no-display" href="#pdp_design_popup">View</a>
    <input type="hidden" id="base_url" value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK) ?>" />
	<input type="hidden" id="url_site" value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK) ?>" />
    <input type="hidden" id="current_product_id" value="<?php echo $productId ?>" />
	<input type="hidden" id="pdp_design_action" value="<?php echo $action ?>" />
	<input type="hidden" id="product_url" value="<?php echo $currentProduct->getProductUrl(); ?>" />
	<input type="hidden" id="pdp_design_share" value="<?php echo $shareId ?>" />
	<input type="hidden" id="pdp_btn_action" value=""/>
	<?php
		$itemCartId = "";
		if (Mage::app()->getRequest()->getActionName() == "configure") {
			$itemCartId = Mage::app()->getRequest()->getParam('id');
		}
	?>
	<input type="hidden" id="cart_item_id" value="<?php echo $itemCartId ?>" />
</div>
<span class="pdp_loading no-display"><span>Please wait...</span></span>
<div class="design-btn">
    <span class="button create-sample-btn design-product" id="design_product_<?php echo $productId ?>"><?php echo $this->__('Design Product'); ?></span>
    <!--<span class="button create-sample-btn" id="design_product_<?php //echo $productId ?>"><?php //echo $this->__('Custom this product'); ?></span>-->
</div>
<div class="no-display">
	<div id="pdp_design_popup"></div>
</div>